### ISSUE TITLE
WARN  deprecated: .Site.Social was deprecated

### ISSUE THREAD

**Issue by WinPoss** [sonnycalcr/sonnycalcr.github.io#5]
`WARN  deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in a future release. Use .Site.Params instead.   `

Every time when I run the hugo website from the command line, I get this prompt, is there a file that needs to be modified?

**Comment by sonnycalcr** [comment]
Just a warning, this problem was imported by the theme papermod, you could have a look at this [issue](https://github.com/adityatelange/hugo-PaperMod/issues/1573) of hugo-papermod itself.
